### ISSUE TITLE
Morning sesssion peer-to-peer review

### ISSUE THREAD

**Issue by jodrack07** [Thermiee/Portfolio#10]
Good job so far but some changes and improvements need to make:

1.Try to provide a more describes PR title and description that includes the technologies and tools you used during the project implementation and what you more from them.

2.Fix the sidebar container content on the Desktop Skeleton

3.Fix the About me session

4.Fix the contact form inputs fields to meet the Figma design. They must not take the 100% of the container

**Comment by Thermiee** [comment]
Hello @joseph07-drack Thanks for the review i fixed it all now.

**Comment by jodrack07** [comment]
Congratulations man
